from BaseClasses import Region, MultiWorld
from AutoWorld import World
from .Locations import PTLocation
from .Options import PTOptions
from . import PTChars
from typing import List, Dict, Tuple


def create_regions(world: World, multiworld: MultiWorld, player: int):
    class PTRegion(Region):
        """Region constructor pre-filled with redundant data. Only argument is region name"""
        def __init__(self, name: str):
            super().__init__(self, name, player, multiworld)

    pt_regions: Dict[str, PTRegion] = {}

    pt_rooms: List[str] = [
        # "room_name": ((connecting room name, connection name))
        #
        # connections should be named after their in-game door letter, except hub areas
        #
        # generally, and for completeness, individual rooms will be separate regions
        # we can split really big rooms into pieces if it makes sense
        # we can also ignore rooms that don't make sense to individualize like the pizzaface hall
        # we have to duplicate rooms accessible in both pre-escape and escape, due to generator quirks
        #       place items wherever they are first accessible
        #       for example, place john gutter secret 2 in pre-escape even though it's accessible in the escape
        # use internal room names by convention, since these rooms don't have any other recognizable names
        #       (unless you really want to call half the rooms "PIZZA TOWER ISLAND" for some reason)
        # don't forget pumpkins cuz they don't show up on the sr wiki
        # procedure for lap 2 for each level:
        #       - make a lap region (even if the level doesn't have a lap room)
        #       - give it a one-way transition into the escape start room
        #       - place a lap 2 event item at the lap region

        # hub world floors
        # TODO make tower_1 the starting region in init.py
        # TODO connect these to boss regions whenever
        "tower_1",
        "tower_2",
        "tower_3",
        "tower_3 Deep Dish 9 Area",
        "tower_4",
        "tower_5",
        "tower_5 WAR Area",

        # john gutter
        "entrance_1",
        "entrance_2",
        "entrance_3",
        "entrance_4",
        "entrance_5",
        "entrance_6",
        "entrance_7",
        "entrance_8",
        "entrance_9",
        "entrance_10", # start escape
        "entrance_9 ESC",
        "entrance_8 ESC",
        "entrance_7 ESC",
        "entrance_6 ESC",
        "entrance_6c",
        "entrance_5 ESC",
        "entrance_4 ESC",
        "entrance_3 ESC",
        "entrance_2 ESC",
        "entrance_1 ESC",
        "entrance LAP",

        # for spoiler log clarity, name secrets as normal, not by their internal name
        # this will be done through a loop

        # pizzascape
        "medieval_1",
        "medieval_2",
        "medieval_3",
        "medieval_3b",
        "medieval_4",
        "medieval_5",
        "medieval_6",
        "medieval_7",
        "medieval_8",
        "medieval_9",
        "medieval_9b",
        "medieval_10", # start escape
        "medieval_9b ESC",
        "medieval_9 ESC",
        "medieval_8 ESC",
        "medieval_7 ESC",
        "medieval_6 ESC",
        "medieval_5 ESC",
        "medieval_4 ESC",
        "medieval_3b ESC",
        "medieval_2 ESC",
        "medieval_1 ESC",
        "medieval LAP",
        # "medieval" doesnt even look like a real word anymore

        # ancient cheese
        "ruin_1",
        "ruin_2",
        "ruin_3",
        "ruin_3b",
        "ruin_4",
        "ruin_5",
        "ruin_6",
        "ruin_7",
        "ruin_8",
        "ruin_10", # room where you run in a straight line. room order gets weird here so pay attention
        "Top of ruin_11",
        "ruin_9",
        "Bottom of ruin_11", # start escape
        "ruin_12",
        "ruin_13",
        "ruin_8 ESC",
        "ruin_7 ESC",
        "ruin_6 ESC",
        "ruin_5 ESC",
        "ruin_1 ESC",
        "ruin LAP",

        # bloodsauce dungeon
        "dungeon_1",
        "dungeon_2",
        "dungeon_3",
        "dungeon_4",
        "dungeon_5",
        "dungeon_6",
        "dungeon_7",
        "dungeon_8",
        "dungeon_9",
        "dungeon_10", # start escape
        "dungeon_9 ESC",
        "dungeon_8 ESC",
        "dungeon_7 ESC",
        "dungeon_6 ESC",
        "dungeon_5 ESC",
        "dungeon_4 ESC",
        "dungeon_3 ESC",
        "dungeon_2 ESC",
        "dungeon_1 ESC",
        "dungeon LAP",

        # oregano desert
        "badland_1",
        "badland_2",
        "badland_3",
        "badland_4",
        "badland_5 1F",
        "badland_5a",
        "badland_5 2F",
        "badland_5b",
        "badland_5 3F",
        "badland_8",
        "badland_8b",
        "badland_9", # start escape
        "badland_10",
        "badland_6",
        "badland_7",
        "badland_3 ESC",
        "badland_2 ESC",
        "badland_1 ESC",
        "badland LAP",

        # wasteyard
        "graveyard_1",
        "graveyard_2",
        "graveyard_3",
        "graveyard_4",
        "graveyard_5",
        "graveyard_5b",
        "graveyard_5c",
        "graveyard_6", # start escape
        "graveyard_5c ESC",
        "graveyard_3 ESC",
        "graveyard_2 ESC",
        "graveyard_7",
        "graveyard_8",
        "graveyard_9",
        "graveyard_9b",
        "graveyard_10",
        "graveyard_1 ESC",
        "graveyard LAP",

        # fun farm
        "farm_2",
        "farm_1",
        "farm_3",
        "farm_4",
        "farm_4b",
        "farm_5",
        "farm_7",
        "farm_8",
        "farm_6",
        "farm_9",
        "farm_10",
        "farm_9b",
        "farm_11", # start escape
        "farm_12",
        "farm_12b",
        "farm_13",
        "farm_4 ESC",
        "farm_1 ESC",
        "farm_2 ESC",
        "farm LAP",

        # fastfood saloon
        "saloon_1",
        "saloon_2",
        "saloon_2b",
        "saloon_3b",
        "saloon_3",
        "saloon_4",
        "saloon_4b",
        "saloon_5b",
        "saloon_5",
        "saloon_6b",
        "saloon_6", # start escape
        "saloon_5 ESC",
        "saloon_4 ESC",
        "saloon_3 ESC",
        "saloon_2 ESC",
        "saloon_1 ESC",
        "saloon LAP",

        # crust cove
        "plage_entrance",
        "plage_lap",
        "plage_beach1",
        "plage_shipmain",
        "plage_ship1",
        "plage_ship2",
        "plage_ship3",
        "plage_beach2",
        "plage_cavern1",
        "plage_cavern2", # start escape
        "plage_cavern3",
        "plage_beach2 ESC",
        "plage_shipmain ESC",
        "plage_shiptop",
        "plage_beach1 ESC",
        "plage_entrance ESC",
        "plage LAP",

        # gnome forest
        "forest_1",
        "forest_2",
        "forest_3",
        "forest_G1",
        "forest_G1b",
        "forest_G2",
        "forest_G3",
        "forest_5",
        "forest_6",
        "forest_7",
        "forest_G4", 
        "forest_G5",
        "forest_8",
        "forest_9",
        "forest_10",
        "forest_12",
        "forest_14",
        "forest_15",
        "forest_16",
        "forest_17",
        "forest_john", # start escape
        "forest_escape2",
        "forest_G5 ESC",
        "forest_escape1",
        "forest_G3 ESC",
        "forest_G2 ESC",
        "forest_G1 ESC",
        "forest_3 ESC",
        "forest_2 ESC",
        "forest_1 ESC",
        "forest LAP",

        # deez dish 9
        "space_1",
        "space_2",
        "space_3",
        "space_4",
        "space_5",
        "space_6",
        "space_7",
        "space_8",
        "space_9", # start escape
        "space_10",
        "space_11",
        "space_11b",
        "space_12",
        "space_1 ESC",
        "space LAP",

        # golf
        "minigolf_1",
        "minigolf_2",
        "minigolf_3",
        "minigolf_4",
        "minigolf_5",
        "minigolf_6",
        "minigolf_7",
        "minigolf_8", # start escape; if expert logic and conditions are met, link directly to "minigolf_4 ESC"
        "minigolf_9",
        "minigolf_10",
        "minigolf_11", # minigolf_8 ESC is included here
        "minigolf_4 ESC",
        "minigolf_3 ESC",
        "minigolf_2 ESC",
        "minigolf_1 ESC",
        "minigolf LAP",

        # pig city
        "street_intro",
        "street_1",
        "street_house1",
        "street_2",
        "street_house2",
        "street_3",
        "street_house3",
        "street_bacon",
        "street_jail",
        "street_4",
        "street_house4",
        "street_5",
        "street_house5",
        "street_john", # start escape
        "street_5 ESC",
        "street_4 ESC",
        "street_jail ESC",
        "street_3 ESC",
        "street_2 ESC",
        "street_1 ESC",
        "street_intro ESC",
        "street LAP",

        # peppibot factory - most of these rooms are split in halves so they'll have weird names
        "industrial_1",
        "Left side of industrial_2",
        "Left side of industrial_3",
        "Left side of industrial_4",
        "industrial_5", # start escape
        "Right side of industrial_4",
        "Right side of industrial_3",
        "Right side of industrial_2",
        "industrial_1 ESC",
        "industrial LAP",

        # oh shit!
        "sewer_1",
        "sewer_2",
        "sewer_3",
        "sewer_4",
        "sewer_5",
        "sewer_6",
        "sewer_7",
        "sewer_8", # start escape
        "sewer_9",
        "sewer_10",
        "sewer_11",
        "sewer_12",
        "sewer_2 ESC",
        "sewer_1 ESC",
        "sewer LAP",

        # rrf - noise's route looks way different so be careful
        # peppino is expected to lose satan's choice at lap 2 so we need different rules to account for that
        # we can achieve this by placing level complete, treasure, and secret 3 at pillar john and treating
        #       the normal escape route as lap 2 only
        "freezer_1",
        "freezer_2",
        "freezer_3",
        "freezer_4",
        "freezer_5",
        "freezer_6",
        "freezer_6 Unfrozen",
        "freezer_7",
        "freezer_9",
        "freezer_9 Unfrozen"
        "freezer_12",
        "freezer_13",
        "freezer_15",
        "freezer_16",
        "freezer_16 Unfrozen"
        "freezer_17",
        "freezer_escape1", # start escape; place level completion here since peppino should have satan's by now
        "freezer_13 ESC", # this room and below should be lap 2 only
        "freezer_12 ESC",
        "freezer_9 ESC",
        "freezer_7 ESC",
        "freezer_4 ESC",
        "freezer_3 ESC",
        "freezer_2 ESC",
        "freezer_1 ESC",

        # pizzascare
        "chateau_1",
        "chateau_2",
        "chateau_3",
        "chateau_4",
        "chateau_5",
        "chateau_6",
        "chateau_7",
        "chateau_8",
        "chateau_9", # start escape
        "chateau_8 ESC",
        "chateau_7 ESC", # also includes chateau_6 ESC
        "chateau_5 ESC",
        "chateau_2 ESC",
        "chateau_2b",
        "chateau_1 ESC",
        "chateau LAP",

        # dmas
        "kidsparty_1",
        "kidsparty_floor1_1",
        "kidsparty_floor1_2",
        "kidsparty_floor1_3",
        "kidsparty_floor2_1",
        "kidsparty_floor2_2",
        "kidsparty_floor2_3",
        "kidsparty_floor3_1",
        "kidsparty_floor3_2",
        "kidsparty_floor3_3",
        "kidsparty_floor4_1",
        "kidsparty_floor4_2", 
        "kidsparty_floor4_3",
        "kidsparty_john", # start escape
        "kidsparty_floor4_3 ESC",
        "kidsparty_escape1",
        "kidsparty_escape2",
        "kidsparty_floor1_3 ESC",
        "kidsparty_floor1_2 ESC",
        "kidsparty_floor1_1 ESC",
        "kidsparty_1 ESC",

        # war - no john in this level so rules are gonna be easier to write
        "war_1",
        "war_2",
        "war_3",
        "war_6",
        "war_7",
        "war_8",
        "war_9",
        "war_10",
        "war_11",
        "war_12",
        "war_12b",
        "war_13",
        "war LAP",

        # ctop - like war, this level is linear so rules are easy
        "tower_finalhallway",
        "tower_5 ESC",
        "tower_escape1",
        "tower_escape2",
        "tower_escape3",
        "tower_4 ESC"
        "tower_escape4",
        "tower_escape5",
        "tower_escape6",
        "tower_3 ESC",
        "tower_escape7",
        "tower_escape8",
        "tower_escape9",
        "tower_2 ESC",
        "tower_escape10",
        "tower_escape11",
        "tower_escape12",
        "tower_1 ESC",
        "tower_johngutterhall",
        "tower_entrancehall"
    ]

    pt_connections: List[Tuple[str]] = [ # (connecting room, door letter)
        ("entrance_2", "entrance_lap"),
        ("entrance_1", "entrance_3"),
        ("entrance_2", "entrance_4"),
        ("entrance_3", "entrance_5"),
        ("entrance_4", "entrance_6"),
        ("entrance_6c", "entrance_7"),
        ("entrance_6", "entrance_8"),
        ("entrance_7", "entrance_9"),
        ("entrance_8", "entrance_10"),
        ("entrance_9"),
        ("entrance_5")
    ]

    pt_locations: Dict[str, Tuple[str]] = {
        # let's try using event items for level progression:
        #       "[level] Gerome"
        #       "[level] Key"
        #       "[level] Lap 2 Portal"
        #       ...and others for chef tasks, as needed
        "tower_1": None,
        "tower_2": None,
        "tower_3": None,
        "tower_3 Deep Dish 9 Area": None,
        "tower_4": None,
        "tower_5": None,
        "tower_5 WAR Area": None,

        
        "entrance_1": None,
        "entrance_2": ("John Gutter Mushroom Toppin"),
        "entrance_3": None,
        "entrance_4": None,
        "entrance_5": ("John Gutter Cheese Toppin"),
        "entrance_6": ("John Gutter Tomato Toppin", "John Gutter Secret 1"),
        "entrance_7": ("John Gutter Pumpkin"),
        "entrance_8": ("John Gutter Sausage Toppin"),
        "entrance_9": ("John Gutter Pineapple Toppin", "John Gutter Secret 2"),
        "entrance_10": None, 
        "entrance_9 ESC": None,
        "entrance_8 ESC": None,
        "entrance_7 ESC": ("John Gutter Treasure"),
        "entrance_6 ESC": None,
        "entrance_6c": ("John Gutter Secret 3", "Chef Task: John Gutted"),
        "entrance_5 ESC": None,
        "entrance_4 ESC": None,
        "entrance_3 ESC": None,
        "entrance_2 ESC": None,
        "entrance_1 ESC": ("Chef Task: Let's Make This Quick", "Chef Task: Primate Rage"),
        "entrance LAP": None,

        
        "medieval_1": ("Pizzascape Mushroom Toppin"),
        "medieval_2": None,
        "medieval_3": ("Pizzascape Cheese Toppin"),
        "medieval_3b": ("Chef Task: Spherical"),
        "medieval_4": ("Pizzascape Tomato Toppin", "Pizzascape Secret 1", "Chef Task: Spoonknight"),
        "medieval_5": None,
        "medieval_6": ("Pizzascape Sausage Toppin", "Pizzascape Secret 2"),
        "medieval_7": ("Pizzascape Pineapple Toppin"),
        "medieval_8": None,
        "medieval_9": None,
        "medieval_9b": None,
        "medieval_10": ("Chef Task: Shining Armor"), 
        "medieval_9b ESC": None,
        "medieval_9 ESC": None,
        "medieval_8 ESC": None,
        "medieval_7 ESC": None,
        "medieval_6 ESC": None,
        "medieval_5 ESC": ("Pizzascape Treasure"),
        "medieval_4 ESC": None,
        "medieval_3b ESC": ("Pizzascape Secret 3"),
        "medieval_2 ESC": None,
        "medieval_1 ESC": None,
        "medieval LAP": None,
        

        
        "ruin_1": None,
        "ruin_2": ("Ancient Cheese Mushroom Toppin", "Ancient Cheese Secret 1", "Chef Task: Delicacy"),
        "ruin_3": None,
        "ruin_3b": None,
        "ruin_4": None,
        "ruin_5": ("Ancient Cheese Cheese Toppin"),
        "ruin_6": ("Ancient Cheese Tomato Toppin"),
        "ruin_7": ("Chef Task: Volleybomb", "Ancient Cheese Secret 2"),
        "ruin_8": ("Ancient Cheese Treasure"),
        "ruin_10": None, 
        "Top of ruin_11": None,
        "ruin_9": ("Ancient Cheese Sausage Toppin"),
        "Bottom of ruin_11": ("Ancient Cheese Secret 3"), 
        "ruin_12": ("Ancient Cheese Pineapple Toppin"),
        "ruin_13": None,
        "ruin_8 ESC": None,
        "ruin_7 ESC": None,
        "ruin_6 ESC": None,
        "ruin_5 ESC": None,
        "ruin_1 ESC": ("Chef Task: Thrill Seeker"),
        "ruin LAP": None,

        
        "dungeon_1": None,
        "dungeon_2": ("Bloodsauce Dungeon Mushroom Toppin"),
        "dungeon_3": ("Bloodsauce Dungeon Cheese Toppin", "Bloodsauce Dungeon Secret 1"),
        "dungeon_4": ("Bloodsauce Dungeon Tomato Toppin"),
        "dungeon_5": ("Bloodsauce Dungeon Secret 2"),
        "dungeon_6": None,
        "dungeon_7": ("Bloodsauce Dungeon Treasure"),
        "dungeon_8": None,
        "dungeon_9": ("Bloodsauce Dungeon Sausage Toppin", "Bloodsauce Dungeon Pineapple Toppin", "Bloodsauce Dungeon Secret 3"),
        "dungeon_10": None, 
        "dungeon_9 ESC": ("Chef Task: Eruption Man"),
        "dungeon_8 ESC": None,
        "dungeon_7 ESC": None,
        "dungeon_6 ESC": None,
        "dungeon_5 ESC": None,
        "dungeon_4 ESC": None,
        "dungeon_3 ESC": None,
        "dungeon_2 ESC": None,
        "dungeon_1 ESC": ("Chef Task: Very Very Hot Sauce", "Chef Task: Unsliced Pizzaman"),
        "dungeon LAP": None,

        
        "badland_1": None,
        "badland_2": ("Chef Task: Peppino's Rain Dance"),
        "badland_3": ("Oregano Desert Mushroom Toppin"),
        "badland_4": ("Oregano Desert Secret 1"),
        "badland_5 1F": None,
        "badland_5a": ("Oregano Desert Cheese Toppin"),
        "badland_5 2F": None,
        "badland_5b": None,
        "badland_5 3F": None,
        "badland_8": ("Oregano Desert Secret 2"),
        "badland_8b": None,
        "badland_9": ("Oregano Desert Tomato Toppin"), 
        "badland_10": ("Oregano Desert Sausage Toppin", "Oregano Desert Treasure"),
        "badland_6": None,
        "badland_7": ("Oregano Desert Pineapple Toppin", "Chef Task: Unnecessary Violence", "Oregano Desert Secret 3"),
        "badland_3 ESC": None,
        "badland_2 ESC": None,
        "badland_1 ESC": ("Chef Task: Alien Cow"),
        "badland LAP": None,

        
        "graveyard_1": None,
        "graveyard_2": ("Wasteyard Mushroom Toppin"),
        "graveyard_3": ("Wasteyard Secret 1"),
        "graveyard_4": ("Wasteyard Cheese Toppin"),
        "graveyard_5": ("Wasteyard Tomato Toppin"),
        "graveyard_5b": None,
        "graveyard_5c": ("Wasteyard Sausage Toppin", "Wasteyard Secret 2"),
        "graveyard_6": ("Wasteyard Treasure"), 
        "graveyard_5c ESC": None,
        "graveyard_3 ESC": ("Wasteyard Secret 3"),
        "graveyard_2 ESC": None,
        "graveyard_7": None,
        "graveyard_8": ("Wasteyard Pineapple Toppin"),
        "graveyard_9": None,
        "graveyard_9b": ("Chef Task: Pretend Ghost"),
        "graveyard_10": ("Chef Task: Alive And Well"),
        "graveyard_1 ESC": ("Chef Task: Ghosted"),
        "graveyard LAP": None,

        
        "farm_2": None,
        "farm_1": None,
        "farm_3": None,
        "farm_4": None,
        "farm_4b": ("Fun Farm Secret 1"),
        "farm_5": None,
        "farm_7": None,
        "farm_8": ("Fun Farm Mushroom Toppin", "Chef Task: Cube Menace"),
        "farm_6": ("Fun Farm Cheese Toppin"),
        "farm_9": None,
        "farm_10": ("Fun Farm Tomato Toppin"),
        "farm_9b": ("Fun Farm Sausage Toppin", "Fun Farm Secret 2"),
        "farm_11": None, 
        "farm_12": ("Chef Task: No One Is Safe"),
        "farm_12b": None,
        "farm_13": ("Fun Farm Pineapple Toppin", "Fun Farm Secret 3"),
        "farm_4 ESC": None,
        "farm_1 ESC": ("Fun Farm Treasure"),
        "farm_2 ESC": ("Chef Task: Good Egg"),
        "farm LAP": None,

        
        "saloon_1": None,
        "saloon_2": ("Fastfood Saloon Mushroom Toppin"),
        "saloon_2b": None,
        "saloon_3b": None,
        "saloon_3": ("Fastfood Saloon Cheese Toppin"),
        "saloon_4": ("Fastfood Saloon Tomato Toppin"),
        "saloon_4b": None,
        "saloon_5b": ("Fastfood Saloon Secret 1"),
        "saloon_5": ("Fastfood Saloon Sausage Toppin", "Fastfood Saloon Secret 2"),
        "saloon_6b": ("Fastfood Saloon Pineapple Toppin"),
        "saloon_6": None, 
        "saloon_5 ESC": None,
        "saloon_4 ESC": None,
        "saloon_3 ESC": ("Fastfood Saloon Treasure"),
        "saloon_2 ESC": ("Fastfood Saloon Secret 3"),
        "saloon_1 ESC": ("Chef Task: Non-Alcoholic", "Chef Task: Royal Flush", "Chef Task: Already Pressed"),
        "saloon LAP": None,

        # place X depending on logic difficulty later
        "plage_entrance": None,
        "plage_lap": None,
        "plage_beach1": ("Crust Cove Mushroom Toppin", "Crust Cove Treasure"),
        "plage_shipmain": ("Chef Task: Blowback"), # blowback here if wallclimb/superjump
        "plage_ship1": None,
        "plage_ship2": ("Crust Cove Cheese Toppin", "Crust Cove Secret 1", "Chef Task: Blowback"), # blowback here if no wallclimb/superjump
        "plage_ship3": None,
        "plage_beach2": ("Crust Cove Tomato Toppin", "Crust Cove Secret 2"),
        "plage_cavern1": None,
        "plage_cavern2": ("Crust Cove Sausage Toppin", "Crust Cove Secret 3"), 
        "plage_cavern3": None,
        "plage_beach2 ESC": None,
        "plage_shipmain ESC": None,
        "plage_shiptop": ("Crust Cove Pineapple Toppin"),
        "plage_beach1 ESC": None,
        "plage_entrance ESC": ("Chef Task: Demolition Expert"),
        "plage LAP": None,

        
        "forest_1": ("Chef Task: Bee Nice"),
        "forest_2": ("Chef Task: Bullseye"),
        "forest_3": None,
        "forest_G1": None,
        "forest_G1b": None,
        "forest_G2": ("Gnome Forest Secret 1"),
        "forest_G3": None,
        "forest_5": None,
        "forest_6": ("Gnome Forest Mushroom Toppin"),
        "forest_7": None,
        "forest_G4": None, 
        "forest_G5": ("Gnome Forest Cheese Toppin"),
        "forest_8": None,
        "forest_9": None,
        "forest_10": ("Gnome Forest Tomato Toppin"),
        "forest_12": ("Gnome Forest Secret 2"),
        "forest_14": None,
        "forest_15": None,
        "forest_16": None,
        "forest_17": ("Gnome Forest Sausage Toppin"),
        "forest_john": None, 
        "forest_escape2": None,
        "forest_G5 ESC": None,
        "forest_escape1": None,
        "forest_G3 ESC": None,
        "forest_G2 ESC": None,
        "forest_G1 ESC": None,
        "forest_3 ESC": ("Gnome Forest Pineapple Toppin", "Gnome Forest Treasure"),
        "forest_2 ESC": None,
        "forest_1 ESC": ("Gnome Forest Secret 3", "Chef Task: Lumberjack"),
        "forest LAP": None,

        
        "space_1": None,
        "space_2": None,
        "space_3": ("Deep Dish 9 Mushroom Toppin", "Deep Dish 9 Secret 1"),
        "space_4": ("Deep Dish 9 Cheese Toppin"),
        "space_5": None,
        "space_6": ("Deep Dish 9 Tomato Toppin"),
        "space_7": ("Deep Dish 9 Secret 2", "Chef Task: Man Meteor"),
        "space_8": ("Deep Dish 9 Sausage Toppin"),
        "space_9": ("Deep Dish 9 Pineapple Toppin"), 
        "space_10": ("Chef Task: Turbo Tunnel"),
        "space_11": None,
        "space_11b": ("Deep Dish 9 Secret 3", "Chef Task: Blast 'Em Asteroids"),
        "space_12": None,
        "space_1 ESC": ("Deep Dish 9 Treasure"),
        "space LAP": None,

        
        "minigolf_1": None,
        "minigolf_2": None,
        "minigolf_3": None,
        "minigolf_4": ("GOLF Mushroom Toppin"),
        "minigolf_5": ("GOLF Cheese Toppin", "GOLF Secret 1"),
        "minigolf_6": ("GOLF Tomato Toppin", "GOLF Secret 2", "Chef Task: Helpful Burger"),
        "minigolf_7": ("GOLF Sausage Toppin", "GOLF Secret 3"),
        "minigolf_8": ("GOLF Pineapple Toppin", "Chef Task: Nice Shot"), 
        "minigolf_9": None,
        "minigolf_10": None,
        "minigolf_11": ("Chef Task: Primo Golfer"), 
        "minigolf_4 ESC": ("GOLF Treasure"),
        "minigolf_3 ESC": None,
        "minigolf_2 ESC": None,
        "minigolf_1 ESC": None,
        "minigolf LAP": None,

        
        "street_intro": None,
        "street_1": None,
        "street_house1": ("The Pig City Mushroom Toppin"),
        "street_2": None,
        "street_house2": ("The Pig City Cheese Toppin", "The Pig City Secret 1"),
        "street_3": None,
        "street_house3": ("The Pig City Tomato Toppin"),
        "street_bacon": ("Chef Task: Pan Fried"),
        "street_jail": None,
        "street_4": ("The Pig City Pumpkin"),
        "street_house4": ("The Pig City Sausage Toppin", "The Pig City Secret 2"),
        "street_5": ("Chef Task: Strike!", "Chef Task: Say Oink!"),
        "street_house5": ("The Pig City Pineapple Toppin", "The Pig City Secret 3"),
        "street_john": None, 
        "street_5 ESC": None,
        "street_4 ESC": None,
        "street_jail ESC": ("The Pig City Treasure"),
        "street_3 ESC": None,
        "street_2 ESC": None,
        "street_1 ESC": None,
        "street_intro ESC": None,
        "street LAP": None,

        # add Whoop This! to wherever peppibot secret 1 ends up
        "industrial_1": None,
        "Left side of industrial_2": ("Peppibot Factory Mushroom Toppin", "Peppibot Factory Secret 1"),
        "Left side of industrial_3": ("Peppibot Factory Cheese Toppin"),
        "Left side of industrial_4": ("Peppibot Factory Tomato Toppin", "Peppibot Factory Secret 2"),
        "industrial_5": ("Peppibot Factory Sausage Toppin", "Peppibot Factory Pumpkin"), 
        "Right side of industrial_4": ("Peppibot Factory Pineapple Toppin"),
        "Right side of industrial_3": ("Peppibot Factory Secret 3", "Chef Task: Unflattening"),
        "Right side of industrial_2": ("Chef Task: There Can Be Only One"),
        "industrial_1 ESC": ("Peppibot Factory Treasure"),
        "industrial LAP": None,

        
        "sewer_1": None,
        "sewer_2": None,
        "sewer_3": ("Oh Shit! Mushroom Toppin", "Oh Shit! Secret 1"),
        "sewer_4": ("Oh Shit! Cheese Toppin"),
        "sewer_5": None,
        "sewer_6": None,
        "sewer_7": ("Oh Shit! Tomato Toppin", "Chef Task: Food Clan"),
        "sewer_8": ("Oh Shit! Secret 2"), 
        "sewer_9": ("Oh Shit! Sausage Toppin"),
        "sewer_10": ("Oh Shit! Treasure"),
        "sewer_11": ("Oh Shit! Pineapple Toppin", "Oh Shit! Secret 3"),
        "sewer_12": None,
        "sewer_2 ESC": None,
        "sewer_1 ESC": ("Chef Task: Can't Fool Me", "Chef Task: Penny Pincher"),
        "sewer LAP": None,

        
        "freezer_1": ("Freezerator Mushroom Toppin"),
        "freezer_2": None,
        "freezer_3": ("Freezerator Cheese Toppin"),
        "freezer_4": None,
        "freezer_5": None,
        "freezer_6": None,
        "freezer_6 Unfrozen": ("Freezerator Tomato Toppin", "Freezerator Secret 1"),
        "freezer_7": None,
        "freezer_9": None,
        "freezer_9 Unfrozen": None,
        "freezer_12": None,
        "freezer_13": ("Freezerator Sausage Toppin"),
        "freezer_15": ("Freezerator Pineapple Toppin", "Freezerator Secret 2"),
        "freezer_16": None,
        "freezer_16 Unfrozen": None,
        "freezer_17": None,
        "freezer_escape1": ("Freezerator Treasure", "Freezerator Secret 3", "Chef Task: Ice Climber", "Chef Task: Frozen Nuggets", "Chef Task: Season's Greetings"), # season's greetings here if player has supertaunt 
        "freezer_13 ESC": None, 
        "freezer_12 ESC": None,
        "freezer_9 ESC": None,
        "freezer_7 ESC": None,
        "freezer_4 ESC": None,
        "freezer_3 ESC": None,
        "freezer_2 ESC": ("Chef Task: Season's Greetings"), # season's greetings here if player does not have supertaunt
        "freezer_1 ESC": None,

        
        "chateau_1": None,
        "chateau_2": ("Pizzascare Pumpkin"),
        "chateau_3": ("Pizzascare Mushroom Toppin"),
        "chateau_4": None,
        "chateau_5": ("Pizzascare Cheese Toppin"),
        "chateau_6": ("Pizzascare Tomato Toppin"),
        "chateau_7": None,
        "chateau_8": ("Pizzascare Sausage Toppin", "Pizzascare Secret 1"),
        "chateau_9": None, 
        "chateau_8 ESC": None,
        "chateau_7 ESC": ("Pizzascare Pineapple Toppin", "Chef Task: Skullsplitter"), 
        "chateau_5 ESC": ("Pizzascare Secret 2"),
        "chateau_2 ESC": None,
        "chateau_2b": ("Pizzascare Treasure"),
        "chateau_1 ESC": ("Pizzascare Secret 3", "Chef Task: Haunted Playground"),
        "chateau LAP": None,

        
        "kidsparty_1": None,
        "kidsparty_floor1_1": None,
        "kidsparty_floor1_2": None,
        "kidsparty_floor1_3": None,
        "kidsparty_floor2_1": None,
        "kidsparty_floor2_2": None,
        "kidsparty_floor2_3": None,
        "kidsparty_floor3_1": None,
        "kidsparty_floor3_2": None,
        "kidsparty_floor3_3": None,
        "kidsparty_floor4_1": None,
        "kidsparty_floor4_2": None, 
        "kidsparty_floor4_3": None,
        "kidsparty_john": None, 
        "kidsparty_floor4_3 ESC": None,
        "kidsparty_escape1": None,
        "kidsparty_escape2": None,
        "kidsparty_floor1_3 ESC": None,
        "kidsparty_floor1_2 ESC": None,
        "kidsparty_floor1_1 ESC": None,
        "kidsparty_1 ESC": None,

        
        "war_1": None,
        "war_2": None,
        "war_3": None,
        "war_6": None,
        "war_7": None,
        "war_8": None,
        "war_9": None,
        "war_10": None,
        "war_11": None,
        "war_12": None,
        "war_12b": None,
        "war_13": None,
        "war LAP": None,

        
        "tower_finalhallway": None,
        "tower_5 ESC": None,
        "tower_escape1": None,
        "tower_escape2": None,
        "tower_escape3": None,
        "tower_4 ESC"
        "tower_escape4": None,
        "tower_escape5": None,
        "tower_escape6": None,
        "tower_3 ESC": None,
        "tower_escape7": None,
        "tower_escape8": None,
        "tower_escape9": None,
        "tower_2 ESC": None,
        "tower_escape10": None,
        "tower_escape11": None,
        "tower_escape12": None,
        "tower_1 ESC": None,
        "tower_johngutterhall": None,
        "tower_entrancehall": None,
    }

    # create regions
    for name in pt_rooms:
        pt_regions[name] = PTRegion(name)

    ########## CONNECTION STARTS HERE ##########

    # name entrances after the in-game door letter they correspond to

    # helper function for fetching regions from the dict
    def get_region(name: str):
        return pt_regions[name]

    # connect john gutter
    